Repository tendermint/fundraising, pull requests merged in 2022-04, with the labels that each got.

#154 refactor: refactor batch auction calculation
  x/fundraising/keeper/match.go
  x/fundraising/keeper/match_test.go
  x/fundraising/types/utils.go
Labels: refactoring

#164 feat: update structs
  .github/workflows/sims.yml
  .github/workflows/test.yml
  Makefile
  README.md
  client/docs/static/openapi.yml
  docs/Explanation/ADR/PROCESS.md
  docs/How-To/api/README.md
  proto/fundraising/fundraising.proto
  proto/fundraising/genesis.proto
  proto/fundraising/params.proto
  proto/fundraising/query.proto
  proto/fundraising/tx.proto
  x/fundraising/client/cli/query.go
  x/fundraising/client/cli/tx.go
  x/fundraising/client/testutil/suite.go
  x/fundraising/keeper/auction.go
  x/fundraising/keeper/auction_test.go
  x/fundraising/keeper/bid.go
  x/fundraising/keeper/bid_test.go
  x/fundraising/keeper/genesis.go
  x/fundraising/keeper/genesis_test.go
  x/fundraising/keeper/grpc_query.go
  x/fundraising/keeper/grpc_query_test.go
  x/fundraising/keeper/hooks.go
  x/fundraising/keeper/hooks_test.go
  x/fundraising/keeper/keeper_test.go
  x/fundraising/keeper/match_test.go
  x/fundraising/keeper/store.go
  x/fundraising/keeper/store_test.go
  x/fundraising/simulation/operations.go
  x/fundraising/spec/02_state.md
  x/fundraising/spec/03_state_transitions.md
  x/fundraising/spec/04_messages.md
  x/fundraising/spec/08_hooks.md
  x/fundraising/types/allowed_bidder.go
  x/fundraising/types/auction.go
  x/fundraising/types/auction_test.go
  x/fundraising/types/expected_keepers.go
  x/fundraising/types/fundraising.pb.go
  x/fundraising/types/genesis.go
  x/fundraising/types/genesis.pb.go
  x/fundraising/types/genesis_test.go
  x/fundraising/types/hooks.go
  x/fundraising/types/keys.go
  x/fundraising/types/keys_test.go
  x/fundraising/types/match.go
  x/fundraising/types/msgs.go
  x/fundraising/types/msgs_test.go
  x/fundraising/types/params.pb.go
  x/fundraising/types/query.pb.go
  x/fundraising/types/query.pb.gw.go
Labels: enhancement, refactoring

#166 env: add more workflow actions
  .github/dependabot.yml
  .github/workflows/dependency.yml
  .github/workflows/janitor.yml
Labels: env
